name: learning_vcf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - samtools
  - openssl
  - bwa
  - bcftools
  - freebayes
  - snpsift
  - vt
  - vcftools
  - vt
  - vcflib
  - snpeff
  - pandoc
