name: learning_vcf
channels:
  - bioconda
  - anaconda
  - defaults
dependencies:
  - openjdk=8
  - samtools
  - openssl
  - bwa
  - bcftools
  - freebayes
  - snpsift
  - vt
  - vcftools
  - vt
  - vcflib
  - snpeff
  - pandoc
  - r
  - r-essentials
